---
apiVersion: v1
kind: Secret
metadata:
  namespace: social-kyc
  name: social-kyc-secrets
data:
  aws-access-key-id: '__AWS_ACCESS_KEY_ID_REPLACE__b64enc'
  aws-secret-access-key: '__AWS_SECRET_ACCESS_KEY_REPLACE__b64enc'
