export const __esModule: true;
export const form: string;
export const formLabel: string;
export const nameInput: string;
export const subline: string;
export const chooseIdentity: string;
export const explainer: string;
export const ctaLine: string;
export const cta: string;
