export const __esModule: true;
export const container: string;
export const spinner: string;
export const expandableItem: string;
export const expanded: string;
export const processing: string;
export const itemLabel: string;
export const accordion: string;
export const closed: string;
