name: Production release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Current stable staging tag"
        required: true

jobs:
  deploy:
    name: Build image and push to Amazon ECR
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Deploy to kilt cluster
        uses: kodermax/kubectl-aws-eks@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG }}
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: socialkyc
          IMAGE_TAG: ${{ github.sha }}
        with:
          args: set image deployment/socialkyc socialkyc=$ECR_REGISTRY/$ECR_REPOSITORY@${{ github.event.inputs.tag }} -n social-kyc

