name: Production restart

on: workflow_dispatch

jobs:
  deploy:
    name: Restart Production
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v2.4.0

    - name: Deploy to kilt cluster
      uses: kodermax/kubectl-aws-eks@master
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG }}
      with:
        args: rollout restart deployment socialkyc -n social-kyc

