name: Check pull request
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Configure Node and package manager
        uses: actions/setup-node@v3.8.2
        with:
          node-version-file: 'package.json'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --immutable

      - name: Run linter
        run: yarn lint

      - name: Run tests
        run: yarn test --maxWorkers=2

      - name: Build code
        run: yarn build
