name: Staging restart

on: workflow_dispatch

jobs:
  deploy:
    name: Restart staging
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Deploy to kilt cluster
      uses: kodermax/kubectl-aws-eks@master
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG }}
      with:
        args: rollout restart deployment social-kyc-stg -n social-kyc

